### ISSUE TITLE
error when run  npm install 

### ISSUE THREAD

**Issue by italodl** [alephium/mining-pool#28]
idl@alephium:~/mining-pool-1.1.0$ npm install
npm ERR! code 1
npm ERR! path /home/idl/mining-pool-1.1.0/node_modules/bignum
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@14.18.3 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/idl/mining-pool-1.1.0/node_modules/bignum/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/idl/.cache/node-gyp/14.18.3/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/idl/.cache/node-gyp/14.18.3',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/idl/.cache/node-gyp/14.18.3/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/idl/mining-pool-1.1.0/node_modules/bignum',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.4.0-96-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/idl/mining-pool-1.1.0/node_modules/bignum
npm ERR! gyp ERR! node -v v14.18.3
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

**Comment by italodl** [comment]
I have used idl account (no root) . 

node 14.18.3,  npm 8.3.2,  javac 11.0.13, Redis server v=5.0.7  on ubuntu 20.04 LTS

**Comment by italodl** [comment]
I have used idl account (no root) .

node 14.18.3, npm 8.3.2, javac 11.0.13, Redis version:6.2.6 on ubuntu 20.04 LTS

**Comment by Lbqds** [comment]
Can you try to install bignum separately? `npm install --save bignum`, then `npm update`.

**Comment by italodl** [comment]
no, not work already exists

alephium:/# npm install --save bignum
npm ERR! Tracker "idealTree" already exists

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-27T07_33_40_744Z-debug-0.log

alephium:/# more /root/.npm/_logs/2022-01-27T07_33_40_744Z-debug-0.log
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--save', 'bignum' ]
1 info using npm@8.3.2
2 info using node@v14.18.3
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 40ms
6 timing config:load:builtin Completed in 41ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 4ms
18 timing config:load Completed in 52ms
19 timing npm:load:configload Completed in 52ms
20 timing npm:load:setTitle Completed in 1ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:display Completed in 4ms
23 verbose logfile /root/.npm/_logs/2022-01-27T07_33_40_744Z-debug-0.log
24 timing npm:load:logFile Completed in 7ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 65ms
28 timing arborist:ctor Completed in 1ms
29 timing arborist:ctor Completed in 0ms
30 timing idealTree:init Completed in 11ms
31 timing idealTree:userRequests Completed in 2ms
32 silly idealTree buildDeps
33 timing idealTree Completed in 15ms
34 timing command:install Completed in 38ms
35 verbose stack Error: Tracker "idealTree" already exists
35 verbose stack     at Arborist.[_onError] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/tracker.js:107:11)
35 verbose stack     at Arborist.addTracker (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/tracker.js:31:21)
35 verbose stack     at Arborist.[buildDeps] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:782:10)
35 verbose stack     at Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:215:29)
35 verbose stack     at async Promise.all (index 1)
35 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:151:5)
35 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:157:5)
35 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:66:5)
36 verbose cwd /
37 verbose Linux 5.4.0-96-generic
38 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "bignum"
39 verbose node v14.18.3
40 verbose npm  v8.3.2
41 error Tracker "idealTree" already exists
42 verbose exit 1
43 timing npm Completed in 394ms
44 verbose unfinished npm timer reify 1643268821088
45 verbose unfinished npm timer reify:loadTrees 1643268821106
46 verbose unfinished npm timer idealTree:buildDeps 1643268821121
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     /root/.npm/_logs/2022-01-27T07_33_40_744Z-debug-0.log

**Comment by darkjorse1975** [comment]
Using Windows 10 
I have had the same problem with the bignum installation. after a lot of trial and error I still have not found a solution. but I hope the following might help someone find a solution. 
I run ![image](https://user-images.githubusercontent.com/101584152/160484166-dbece406-3edd-43e9-a46e-7e904178016d.png)
then ![image](https://user-images.githubusercontent.com/101584152/160484072-9d84842e-f56f-40c4-b45e-256ac4b32158.png)
and this is the result:
![image](https://user-images.githubusercontent.com/101584152/160485334-768ab989-bf32-4135-b033-30b7e6b01af0.png)
